In [1]:
import os, glob
import numpy as np
import pandas as pd
import sys
sys.path.insert(0, "../src")
import auxilary_functions as f
from generation_algorithm import *
import subprocess
import csv
import matplotlib.pyplot as plt
import json

cfg_file = "../src/config-ecoli.json"

sizes = ['500', '750', '1000']
os.chdir('../networks/')

In [2]:
def load_ffl_based_component():
    with open(cfg_file, 'r') as j:
        config_file = json.loads(j.read())
            
        interaction_matrix = f.get_interaction_matrix(config_file)
        motifs, counter = f.motif_search(config_file, interaction_matrix, batch_size=10000)
        motifs_orig = motifs["030T"]

        ffl_nodes = list(set(sum([list(map(int, x.split("_"))) for x in motifs_orig], [])))
        interaction_matrix_ffl = np.zeros((len(ffl_nodes), len(ffl_nodes)))
        for motif in motifs_orig:
            motif = f.split_motif(motif)
            motif_new = list(ffl_nodes.index(x) for x in motif)
            interaction_matrix_ffl[np.ix_(motif_new, motif_new)] = \
            interaction_matrix[np.ix_(motif, motif)]
        interaction_matrix_ffl.shape, interaction_matrix_ffl.sum()

        # Vertex-based motif network on FFL
        motifs_network = f.build_vmn(motifs_orig, verbose=True)
        V = nx.Graph(motifs_network)
        nx.is_connected(V)
        return interaction_matrix, motifs_orig, motifs_network, interaction_matrix_ffl

In [3]:
substrate_matrix1 = get_network_nucleus(
        yeast_matrix, ffl_motif, ffl_component, min_size=7, random_seed=19
    )
substrate_matrix2 = get_network_nucleus(
        yeast_matrix, ffl_motif, ffl_component, min_size=7, random_seed=30
    )

NameError: name 'yeast_matrix' is not defined

In [147]:
substrate_matrix1

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0.]])

In [6]:
substrate_matrix2 = np.array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0.]])

In [9]:
substrate_matrix2.sum()

9.0

In [150]:
full_substrate = np.zeros(shape=(substrate_matrix1.shape[0]+substrate_matrix2.shape[0],substrate_matrix1.shape[0]+substrate_matrix2.shape[0]))

In [151]:
full_substrate[0:substrate_matrix1.shape[0], 0:substrate_matrix1.shape[0]] = substrate_matrix1
full_substrate[substrate_matrix1.shape[0]:substrate_matrix1.shape[0]+substrate_matrix2.shape[0], substrate_matrix1.shape[0]:substrate_matrix1.shape[0]+substrate_matrix2.shape[0]] = substrate_matrix2

In [152]:
full_substrate

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.

In [10]:
in_degrees = {'both1': 1, 'both2': 2, 'only_x': 100}
out_degrees = {'both1': 10, 'both2': 20, 'only_y': 200}

all_degrees = {k: in_degrees.get(k, 0) + out_degrees.get(k, 0) for k in set(in_degrees) | set(out_degrees)}

In [11]:
all_degrees

{'only_x': 100, 'only_y': 200, 'both1': 11, 'both2': 22}

## Convert motifs to FFLs // test

In [2]:
df = f.read_ecoli_network("../networks/stability_analysis_experiment/ecoli/fflatt/250/fflatt_transcriptional_network_0_nodes_250.tsv")
edges = df.astype(str)
edges.columns = ["tf", "tg"]
nodes = sorted(np.unique(np.concatenate((edges.tf.unique(), edges.tg.unique()))))
nodes = pd.DataFrame(data=range(len(nodes)), index=nodes, columns=["idx"])
edges_ = edges.join(nodes, on="tf").join(nodes, on="tg", lsuffix="_tf", rsuffix="_tg")
np_edges = edges_[["idx_tg", "idx_tf"]].values
interaction_matrix_test = f.build_Tnet(np_edges, len(nodes))

In [3]:
interaction_matrix_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
def filter_for_two_edge_motif(substrate_matrix, config_file):
    matrix_motifs, motifs_stats = f.motif_search(config_file, substrate_matrix, batch_size=10000)
    original_sum = substrate_matrix.sum()
    
    #iterate over all 3-node loops in network
    #!Note
    #deletion of 021C leads to 
    #for motif_type in [matrix_motifs['021U'], matrix_motifs['021C'], matrix_motifs['021D']]:
    for motif_type in [matrix_motifs['021C']]:
        inner_counts = 0
        print(motif_type)
        for motif in motif_type:
            print(motif)
            #iterate over all nodes in motif
            nodes = motif.split('_')
            out_degrees = {}
            in_degrees = {}
            for node in nodes:
                #calculate out-degree
                out_degrees[node] = substrate_matrix[int(node),:].sum()
                in_degrees[node] = substrate_matrix[:,int(node)].sum()
                
            #sort by out-degree
            out_degrees = {k: v for k, v in sorted(out_degrees.items(), key=lambda item: item[1])}
            in_degrees = {k: v for k, v in sorted(in_degrees.items(), key=lambda item: item[1])}
            
            nodes_out = list(out_degrees.keys())
            nodes_in = list(in_degrees.keys())
            
            all_degrees = {k: in_degrees.get(k, 0) + out_degrees.get(k, 0) for k in set(in_degrees) | set(out_degrees)}
            all_degrees = {k: v for k, v in sorted(all_degrees.items(), key=lambda item: item[1])}
            
            nodes_all = list(all_degrees.keys())
            
            #convert 021U to FFL               
            substrate_matrix[int(nodes_all[1]),int(nodes_all[2])] = 1
            inner_counts +=1
            
            #substrate_matrix[int(nodes_out[0]),int(nodes_out[2])] = 0
            
            #counter // do sum of the matrix instead to calculate the number of added edges
            
        print(f"number_of_motif_substitutions: {inner_counts}")
        
    for motif_type in [matrix_motifs['021D']]:
        inner_counts = 0
        print(motif_type)
        for motif in motif_type:
            #print(motif)
            #iterate over all nodes in motif
            nodes = motif.split('_')
            out_degrees = {}
            in_degrees = {}
            for node in nodes:
                #calculate out-degree
                out_degrees[node] = substrate_matrix[int(node),:].sum()
                in_degrees[node] = substrate_matrix[:,int(node)].sum()
                
            #sort by out-degree
            out_degrees = {k: v for k, v in sorted(out_degrees.items(), key=lambda item: item[1])}
            in_degrees = {k: v for k, v in sorted(in_degrees.items(), key=lambda item: item[1])}
            
            nodes_out = list(out_degrees.keys())
            nodes_in = list(in_degrees.keys())
            
            all_degrees = {k: in_degrees.get(k, 0) + out_degrees.get(k, 0) for k in set(in_degrees) | set(out_degrees)}
            all_degrees = {k: v for k, v in sorted(all_degrees.items(), key=lambda item: item[1])}
            
            nodes_all = list(all_degrees.keys())
            
            #convert 021U to FFL
            substrate_matrix[int(nodes_in[1]),int(nodes_in[2])] = 1
            inner_counts +=1
            
            #substrate_matrix[int(nodes_out[0]),int(nodes_out[2])] = 0
            
            #counter // do sum of the matrix instead to calculate the number of added edges
            
        print(f"number_of_motif_substitutions: {inner_counts}")
        
    loops_edges = substrate_matrix.sum() - original_sum
        
    return loops_edges, substrate_matrix

In [5]:
cfg = f.get_actual_parametrization("../src/config.json")
smth, actual_matrix = filter_for_two_edge_motif(interaction_matrix_test, cfg)

['9_156_185', '12_39_240', '2_103_185', '56_64_157', '106_114_158', '2_138_185', '145_174_185', '16_194_240', '2_9_185', '78_88_97', '2_22_96', '86_185_218', '170_184_229', '78_88_182', '7_113_201', '32_69_178', '39_170_205', '2_57_185', '154_174_185', '2_185_231', '101_158_225', '128_155_228', '37_122_174', '128_155_246', '15_21_172', '39_194_240', '7_43_117', '60_90_246', '2_41_182', '170_180_229', '2_86_218', '88_179_185', '2_185_205', '14_33_235', '37_174_208', '38_158_185', '9_74_172', '121_191_195', '25_93_218', '122_174_196', '100_113_158', '22_153_185', '18_23_108', '10_113_158', '2_54_101', '101_146_225', '113_158_199', '2_185_214', '22_158_185', '2_131_185', '126_158_222', '3_118_158', '16_77_194', '180_218_229', '27_60_185', '2_59_185', '2_134_185', '2_52_74', '155_210_246', '2_176_185', '70_174_208', '184_196_229', '40_126_222', '180_196_229', '14_113_158', '33_158_187', '96_113_158', '2_133_185', '70_174_206', '43_83_212', '37_174_185', '23_164_185', '29_185_225', '25_124_

number_of_motif_substitutions: 13696


In [6]:
matrix_motifs, motifs_stats = f.motif_search(cfg, actual_matrix, batch_size=10000)

In [7]:
motifs_stats

{'021C': 342, '021D': 18389, '021U': 270, '030C': 2, '030T': 252}

In [21]:
motifs_stats

{'021C': 1206, '021D': 11076, '021U': 32, '030C': 1, '030T': 700}

In [8]:
motifs_stats['021C']

342